# Global configuration for the Jekyll site
title: "My Front-End Projects"
baseurl: "" # Base URL for the site, leave it empty for the root

# Markdown options
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Directory settings
source: .
destination: ./_site

# Exclude files and directories from the site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-sass-converter
  - jekyll-paginate

# Build settings
future: true
verbose: true

# Deployment settings
github:
  is_project_page: true
  repository_url: https://github.com/AshishKhatri84/FRONT-END
  publish_dir: ./_site
